### ISSUE TITLE
Environment variables for settings

### ISSUE THREAD

**Issue by dgrigg** [clarknelson/craft-recaptcha-3#10]
A nice feature would be having the option to set key/secret fields via a config file or ENV vars:

https://docs.craftcms.com/v3/extend/plugin-settings.html
https://docs.craftcms.com/v3/extend/environmental-settings.html#validation

**Comment by NikosDevPhp** [comment]
This would be good because now key/secret fields are set to project.yaml which is wrong, because we can't use it in different environments easily.

**Comment by nickolasjadams** [comment]
@NikosDevPhp 
@dgrigg 

What your asking for was added as a default plugin behavior in 2017
https://github.com/craftcms/cms/issues/1096#issuecomment-287754576

I was able to successfully add my key and secret via a config files that referenced my ENV
Doing it this way didn't appear to add the keys to my .yaml files.

Create config/craft-recaptcha-3
```
<?php
return [
	"siteKey" => getenv("GOOGLE_SITEKEY"),
	"secretKey" => getenv("GOOGLE_SECRETKEY")
];
```
and then move your keys in your env.
