### ISSUE TITLE
Invalid site key or not loaded in api.js

### ISSUE THREAD

**Issue by rpeshnegi** [clarknelson/craft-recaptcha-3#15]
`Invalid site key or not loaded in api.js`
Why am i getting this error.

![image](https://user-images.githubusercontent.com/67201900/89982834-0c6d9480-dc94-11ea-9fa8-16277bd98e88.png)

**Comment by clarknelson** [comment]
Did you set your API keys in the craft cms settings?

**Comment by rpeshnegi** [comment]
@clarknelson 

> Did you set your API keys in the craft cms settings?

yep, I did

**Comment by clarknelson** [comment]
Did you resolve the issue or decide on another plugin?

**Comment by rpeshnegi** [comment]
Yes, Resolved it, that was domain problem.

**Comment by clarknelson** [comment]
Thanks for responding :)
