### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [clarknelson/craft-recaptcha-3#18]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `clarknelson\craftrecaptcha3\assetbundles\CraftRecaptcha3\CraftRecaptcha3Asset` located in `./vendor/clarknelson/craft-recaptcha-3/src/assetbundles/craftrecaptcha3/CraftRecaptcha3Asset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

Looks like you’ve already begun to fix this (c60ccbdef9b0704704d614ddca88d5211d492894), however that change is not enough. If you are going to rename the namespace to match the file path (as you’ve done), you will also need to update any places in your code where you are referencing the old namespace, and update to the new namespace.

Otherwise, a simpler fix would be to revert that change, and rename the folder name instead, by running the following command:

```bash
> git mv src/assetbundles/craftrecaptcha3 src/assetbundles/CraftRecaptcha3
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by clarknelson** [comment]
I think I fixed it with 1.1.1 can you confirm?

**Comment by brandonkelly** [comment]
I can confirm that the issue is fixed on your `master` branch, however you haven’t pushed up a `1.1.1` tag yet. The last tag I see is `v1.0.16`.

**Comment by clarknelson** [comment]
Thanks for catching that, I believe i've pushed the tags now

**Comment by brandonkelly** [comment]
Yep, looks good now!
