### ISSUE TITLE
 The file or directory to be published does not exist: clarknelson/craft-recaptcha-3/src/assetbundles/craftrecaptcha3/dist

### ISSUE THREAD

**Issue by CC-RobC** [clarknelson/craft-recaptcha-3#19]
File : vendor/clarknelson/craft-recaptcha-3/src/assetbundles/CraftRecaptcha3/CraftRecaptcha3Asset.php

change : 
`$this->sourcePath = "@clarknelson/craftrecaptcha3/assetbundles/craftrecaptcha3/dist";`
to 
`$this->sourcePath = "@clarknelson/craftrecaptcha3/assetbundles/CraftRecaptcha3/dist";`

**Comment by clarknelson** [comment]
Can you check this is fixed in v1.1.2

**Comment by CC-RobC** [comment]
The current published version is 1.1.1

**Comment by clarknelson** [comment]
sorry can you try again

**Comment by CC-RobC** [comment]
Thanks for your response. Running on 1.1.2 we get the following error
ReflectionException: Class clarknelson\craftrecaptcha3\assetbundles\craftrecaptcha3\CraftRecaptcha3Asset 

please change in vendor/clarknelson/craft-recaptcha-3/src/templates/settings.twig

`{% do view.registerAssetBundle("clarknelson\\craftrecaptcha3\\assetbundles\\craftrecaptcha3\\CraftRecaptcha3Asset") %}`

to 
`{% do view.registerAssetBundle("clarknelson\\craftrecaptcha3\\assetbundles\\CraftRecaptcha3\\CraftRecaptcha3Asset") %}`

**Comment by clarknelson** [comment]
Should be fixed in v1.1.3 can you try on your end?
