### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [clarknelson/craft-recaptcha-3#27]
Hey Clark! Will this plugin get updated for Craft 4?

**Comment by clarknelson** [comment]
sure I will look into what that requires, have not looked at Craft 4 much yet

**Comment by justinholtweb** [comment]
@clarknelson any traction here on a Craft 4 update? I have several sites where this is the only plugin left blocking a move to Craft 4. Thanks for your hard work on the plugin to date!

**Comment by clarknelson** [comment]
I believe I have just released a 4.0.1 version that will work with Craft 4, please let me know if you have any issues.
