### ISSUE TITLE
Unknown "plugin" function.

### ISSUE THREAD

**Issue by alisonweirsmith** [clarknelson/craft-recaptcha-3#4]
Hi,

Installed your plugin with Craft 3.0.36.
Getting above error on attempted front-end installation.

Have not yet set the success and failure methods, but recaptcha is not even rendering.

Thanks

**Comment by clarknelson** [comment]
Can you please use this code in your website to see if it will output the siteKey?

```twig
{% set siteKey = plugin('craft-recaptcha-3').settings.siteKey %}
<script>alert('{{ siteKey }}')</script>
```

I believe this is where the error is coming from

**Comment by thomaslgj** [comment]
I am having the same issue, and your code @clarknelson produced the same error. Seems like the plugin function isn't working.

**Comment by clarknelson** [comment]
The plugin function is not my code

**Comment by clarknelson** [comment]
https://docs.craftcms.com/v3/dev/functions.html#plugin

**Comment by alisonweirsmith** [comment]
> Can you please use this code in your website to see if it will output the siteKey?
> 
> ```
> {% set siteKey = plugin('craft-recaptcha-3').settings.siteKey %}
> <script>alert('{{ siteKey }}')</script>
> ```
> 
> I believe this is where the error is coming from

This doesn't work. Returns the same error:
Unknown 'plugin' function

I honestly just need this plugin to work!

**Comment by angrybrad** [comment]
@alisonweirsmith try using this instead

```
{% set siteKey = craft.app.getModule('craft-recaptcha-3').getSettings().siteKey` %}
<script>alert('{{ siteKey }}')</script>
```

**Comment by angrybrad** [comment]
@alisonweirsmith The `plugin()` Twig function got added in Craft [3.1.0](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#310---2019-01-15). You'll want to update to that.

@clarknelson If you want to keep using it, you should bump the minimum Craft requirements: https://github.com/clarknelson/craft-recaptcha-3/blob/master/composer.json#L34

**Comment by alisonweirsmith** [comment]
Thanks Brad.

Appreciate the feedback.

**Comment by alisonweirsmith** [comment]
Thanks Brad. Noted. Will see about that then.

**Comment by clarknelson** [comment]
Okay i've updated the minimum requirement to 3.1.0

@alisonweirsmith is your issue fixed after updating craft.

**Comment by alisonweirsmith** [comment]
Yes. Upgrade to 3.2 went smoothly and plugin is now working. Thank you.

**Comment by clarknelson** [comment]
Thank you for using my plugin.

@angrybrad thank you so much for your help resolving this :)
