### ISSUE TITLE
"There was a problem requesting the CSRF token from the server"

### ISSUE THREAD

**Issue by noregt** [clarknelson/craft-recaptcha-3#5]
Hi,

With the plugin installed and the tag "{% include ['_recaptcha/frontend'] %}" placed I'm getting this error. CSRF is enabled for Craft.

`There was a problem requesting the CSRF token from the server {error: "Template not found: admin/actions/users/get-remaining-session-time"}`

Craft cms 3.2.4.1

Any idea what to do?

**Comment by clarknelson** [comment]
seems pretty weird, maybe related to this https://craftcms.stackexchange.com/questions/28735/csrf-in-headless-applications

**Comment by clarknelson** [comment]
Here is the relevant code:

```js
window.grecaptcha.ready(function () {
      requestCSRF();
    });
    var requestCSRF = function () {
      var csrfRequest = new XMLHttpRequest();
      csrfRequest.onreadystatechange = function () {
        if (csrfRequest.readyState == XMLHttpRequest.DONE) {
          var response = JSON.parse(csrfRequest.responseText)
          if (csrfRequest.status == 200) {
            requestScore(response.csrfTokenValue);
          } else {
            console.log('There was a problem requesting the CSRF token from the server', response);
          }
        }
      };
      csrfRequest.open("GET", "/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1", true);
      csrfRequest.setRequestHeader("Accept", "application/json");
      csrfRequest.send();
    };
```

**Comment by noregt** [comment]
"Cannot read property 'ready' of undefined" when using this script?

**Comment by clarknelson** [comment]
hmm, the script above is part of what is included when you use `{% include ['_recaptcha/frontend'] %}`, you don't have to put it in yourself

**Comment by clarknelson** [comment]
are you sure you have set the site key and secret key in the settings?

**Comment by noregt** [comment]
Yes, Recaptcha is registering the requests.

**Comment by clarknelson** [comment]
@noregt can you please try this fix and see if it works? https://craftcms.stackexchange.com/a/1018/6981

**Comment by noregt** [comment]
I've set
`'overridePhpSessionLocation' => false`
 And to be sure I set storage chmod to 777 (and later back to 774)

Still the same error I'm afraid

**Comment by clarknelson** [comment]
Can you try `console.log(window.grecaptcha)` and see if the framework is loading.

**Comment by noregt** [comment]
{ready: ƒ, render: ƒ, reset: ƒ, getResponse: ƒ, execute: ƒ}
execute: ƒ (y,r,W,t,m)
getResponse: ƒ (y,r)
ready: ƒ (t)
render: ƒ (y,r,W,t,m,O,z,A,g,v,C,f,b,q,Y,P)
reset: ƒ (y,r,W)
__proto__: Object

Looks okay to me?

**Comment by clarknelson** [comment]
yeah looks okay to me. going to check in with the craft folk again about the action URL

**Comment by clarknelson** [comment]
Have you tried going to the URL?

`/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1`

with your domain in front obviously. I get this error "400 Bad Request: Must accept JSON as a response" but that is expected. Maybe you get something else?

I am thinking maybe your Nginx / Apache config is preventing the URL from being accessed.

**Comment by noregt** [comment]
I've finally figured out the error. As a security measure, I've set the "Control Panel trigger word" in general.php. Removing that solves the error.

I'd like to keep that trigger word?

**Comment by clarknelson** [comment]
You would like to keep that custom trigger word? I will look into accommodating with our plugin :)

**Comment by noregt** [comment]
Thanks!

**Comment by clarknelson** [comment]
I've updated the plugin to 1.0.9 please give it a go!

**Comment by noregt** [comment]
Still same error I'm afraid, still looking for 'admin/actions/users/get-remaining-session-time', where 'admin' should be replaced by the cpTrigger I guess.

**Comment by clarknelson** [comment]
oh, I replaced the "actions" bit not the "admin" bit, I will do the same for "admin"

**Comment by clarknelson** [comment]
Okay i've updated to 1.0.10 can you please try again?

**Comment by noregt** [comment]
Yes it's working now thanks!

**Comment by clarknelson** [comment]
So glad we were able to resolve this, thanks for opening the issue :)
