### ISSUE TITLE
Prevent controller actions meant for the CP from being accessible on the front-end

### ISSUE THREAD

**Issue by paulwaddington** [clarknelson/craft-recaptcha-3#6]
Firstly, thank you for the plugin!

We've used the plugin on a few sites now and started to notice that URLs for the 'actions' directory are being indexed. Would it be possible to implement a solution like the link below?

https://craftcms.stackexchange.com/questions/29406/how-do-i-prevent-a-controller-from-creating-unwanted-routes

**Comment by clarknelson** [comment]
I can add this. How would I test if it's working?

**Comment by paulwaddington** [comment]
From the Stack Exchange answer it suggests 'The non-CP action URLs will now return a 400 error'. If you would like us to test this on one of our staging installations just let me know!

**Comment by clarknelson** [comment]
So what was appearing as a URL? I might be able to ping it.

**Comment by paulwaddington** [comment]
Here you go... https://www.calderdalemusictrust.org.uk/actions/craft-recaptcha-3/default

**Comment by clarknelson** [comment]
Thank you for refreshing my memory. I believe this should be addressed in 1.0.12

**Comment by paulwaddington** [comment]
Just updated the plugin and the previous link I sent is displaying a '503 Service Unavailable'. Thank you for the changes!

**Comment by clarknelson** [comment]
No problem. Thank you for using my plugin and opening the issue.
